INSERT INTO kakeibo.Category (id, name, delete_flg, created_at, updated_at) VALUES
(1, 'Food', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Transport', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Entertainment', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Utilities', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Health', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Miscellaneous', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
