INSERT INTO kakeibo.category (id, name, delete_flg, created_at, updated_at) VALUES
(1, '住居費', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '水道代光熱費', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'その他生活費', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '食費', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '雑費', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
